# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
encoding: utf-8
title: The Complete Guide to Rails Performance
email: nate.berkopec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Complete Guide to Rails Performance course teaches you how to diagnose
  and optimize production Ruby on Rails performance problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.railsspeed.com" # the base hostname & protocol for your site
twitter_username: nateberkopec
github_username: nateberkopec

# Build settings
markdown: kramdown

plugins:
  - jekyll-assets

assets:
  js_compressor:  uglifier
  css_compressor: sass
  prefix: "/assets"
  assets:
    - "*.png"
    - "*.jpg"
    - "main.css"
    - "*.gif"
    - "*.webm"
    - "*.mp4"
  digest: true
  sources:
    - "assets"
    - "assets/css"
    - "assets/img"
    - "assets/js"
    - "_sass"
